---
- name: Set up bastion instance
  hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.yml
    
    - name: Import VPC Output Variables
      include_vars: vars/vpc_output_vars.yml

    - name: Create Vprofile EC2 key
      amazon.aws.ec2_key:
        name: vprofile-key
        region: "{{ region }}"
        state: present
      register: keyout
    
    - name: Save Private Key into file bastion-key.pem
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: keyout.changed
      
    - name: Create Security Group for Bastion
      amazon.aws.ec2_group:
        name: vprofile-bastion-sg
        description: Security group for vprofile bastion
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: bastion_sg

    - name: Insert/Update "Bastion-SG in vars/vpc_output_vars.yml"
      ansible.builtin.blockinfile:
        path: vars/vpc_output_vars.yml
        backup: yes
        block: |
          BastionSG: "{{ bastion_sg.group_id }}"
    
    - name: Create Bastion Instance
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"  
        wait: yes
        wait_timeout: 300
        tags:
          Name: vprofile-bastion
          Project: vprofile
          Owner: Ammar
        exact_count: 1
        filters:
          "tag:Name": "vprofile-bastion"
          "tag:Project": "vprofile"
          "tag:Owner": "Ammar"
        security_groups: 
          - "{{ bastion_sg.group_id }}"
        vpc_subnet_id: "{{ public_subnet1_id }}"
      register: bastion_instance
