- name: Set up bastion instance
  hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt
    
    - name: Import Bastion Variables
      include_vars: vars/bastion_host_setup.txt

    - name: Import VPC Variables
      include_vars: vars/vpc_output_vars

    - name: Create Vprofile EC2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
        state: "{{ state }}"
      register: keyout
    
    - name: Save Private Key into file bastion-key.pem
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: keyout.changed

    - name: Create Security Group for Bastion
      ec2_group:
        name: vprofile-bastion-sg
        description: Security group for vprofile bastion
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: bastion_sg
    
    - name: Create Bastion Instance
      amazon.aws.ec2_instance:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: vprofile-bastion
          Project: vprofile
          Owner: Ammar
        exact_count: 1
        count_tag:
          Name: vprofile-bastion
          Project: vprofile
          Owner: Ammar
        group_id: "{{ bastion_sg.group_id }}"
        vpc_subnet_id: "{{ public_subnet1 }}"
      register: bastion_instance