---
- name: Create VPC
  hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCider }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Print VPC information
      debug:
        var: vpcout

    - name: Create Public Subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cider }}"
        az: "{{ az1 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet1
      register: public_subnet1

    - name: Create Public Subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub2Cider }}"
        az: "{{ az2 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet2
      register: public_subnet2

    - name: Create Public Subnet3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub3Cider }}"
        az: "{{ az3 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet3
      register: public_subnet3

    - name : Create Private Subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub1Cider }}"
        az: "{{ az1 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet1
      register: private_subnet1

    - name : Create Private Subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub2Cider }}"
        az: "{{ az2 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet2
      register: private_subnet2

    - name : Create Private Subnet3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub3Cider }}"
        az: "{{ az3 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet3
      register: private_subnet3

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: vprofile-igw
      register: igw

    - name: Set up Public Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-public-rt
        subnets:
          - "{{ public_subnet1.subnet.id }}"
          - "{{ public_subnet2.subnet.id }}"
          - "{{ public_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: public_rt

    - name: Create NAT Gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet1.subnet.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        wait: yes
        if_exist_do_not_create: yes
        resource_tags:
          Name: vprofile-nat-gw
      register: nat_gw

    - name: Set Up Private Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-private-rt
        subnets:
          - "{{ private_subnet1.subnet.id }}"
          - "{{ private_subnet2.subnet.id }}"
          - "{{ private_subnet3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gw.nat_gateway_id }}"
      register: private_rt

    - name: Store information in file
      debug:
        var: " {{item}} "
      loop:
        - vpcout.vpc.id
        - public_subnet1.subnet.id
        - public_subnet2.subnet.id
        - public_subnet3.subnet.id
        - private_subnet1.subnet.id
        - private_subnet2.subnet.id
        - private_subnet3.subnet.id
        - igw.gateway_id
        - public_rt.route_table_id
        - nat_gw.nat_gateway_id
        - private_rt.route_table_id

    - name: Set ids as the fact Variables
      set_fact:
        vpcid: "{{ vpcout.vpc.id }}"
        public_subnet1: "{{ public_subnet1.subnet.id }}"
        public_subnet2: "{{ public_subnet2.subnet.id }}"
        public_subnet3: "{{ public_subnet3.subnet.id }}"
        private_subnet1: "{{ private_subnet1.subnet.id }}"
        private_subnet2: "{{ private_subnet2.subnet.id }}"
        private_subnet3: "{{ private_subnet3.subnet.id }}"
        igw: "{{ igw.gateway_id }}"
        public_rt: "{{ public_rt.route_table_id }}"
        nat_gw: "{{ nat_gw.nat_gateway_id }}"
        private_rt: "{{ private_rt.route_table_id }}"
   
    - name: Create Variables file for VPC output
      copy:
        content: "vpcid: {{ vpcout.vpc.id }}\n public_subnet1: {{ public_subnet1.subnet.id }}\n public_subnet2: {{ public_subnet2.subnet.id }}\n public_subnet3: {{ public_subnet3.subnet.id }}\n private_subnet1: {{ private_subnet1.subnet.id }}\n private_subnet2: {{ private_subnet2.subnet.id }}\n private_subnet3: {{ private_subnet3.subnet.id }}\n igw: {{ igw.gateway_id }}\n public_rt: {{ public_rt.route_table_id }}\n nat_gw: {{ nat_gw.nat_gateway_id }}\n private_rt: {{ private_rt.route_table_id }}"
        dest: vars/vpc_output_vars         