---
- name: Create VPC
  hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCider }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Print VPC information
      debug:
        var: vpcout

    - name: Create Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cider }}"
        az: "{{ az1 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet1
      register: public_subnet1