---
- name: Create VPC
  hosts: localhost
  connection: local
  tasks:
    - name: Import VPC Variables
      include_vars: vars/vpc_setup.txt

    - name: Create vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCider }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Print VPC information
      debug:
        var: vpcout

    - name: Create Public Subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub1Cider }}"
        az: "{{ az1 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet1
      register: public_subnet1

    - name: Create Public Subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub2Cider }}"
        az: "{{ az2 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet2
      register: public_subnet2

    - name: Create Public Subnet3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PubSub3Cider }}"
        az: "{{ az3 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: yes
        resource_tags:
          Name: vprofile-public-subnet3
      register: public_subnet3

    - name : Create Private Subnet1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub1Cider }}"
        az: "{{ az1 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet1
      register: private_subnet1

    - name : Create Private Subnet2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub2Cider }}"
        az: "{{ az2 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet2
      register: private_subnet2

    - name : Create Private Subnet3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{ PrivSub3Cider }}"
        az: "{{ az3 }}"
        region: "{{ region }}"
        state: "{{ state }}"
        map_public: no
        resource_tags:
          Name: vprofile-private-subnet3
      register: private_subnet3

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: vprofile-igw
      register: igw

    - name: Set up Public Subnet Route Table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        resource_tags:
          Name: vprofile-public-rt
        subnets:
          - "{{ public_subnet1.subnet.id }}"
          - "{{ public_subnet2.subnet.id }}"
          - "{{ public_subnet3.subnet.id }}"
        routes:
          - dest: