- name: Setup vprofile Stack
  hosts: localhost
  connection: local
  tasks:
    - name: import VPC setup Variables
      include_vars: vars/vpc_output_vars.yml

    - name: Import vprofileelasticsetup Variables
      include_vars: vars/vproElasticSetup.yml

    - name: create Vprofile EC2 Key 
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into file vpro-key.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginhey-vpro.pem"
        mode: 0600
      when: vprokey_out.changed

    - name: Create Load Balancer Security Group
      ec2_group:
        name: vpro-elb-sg
        description: Allow Port 80 from anywhere
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: elb_sg_out

    - name: Create EC2 Security Group for Vprofile Stack
      ec2_group:
        name: vprostack-sg
        description: Allow Port 22 from anywhere
        vpc_id: "{{ vpcid }}"
        region: "{{ region }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ elb_sg_out.group_id }}"
          
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSG }}"
          
      register: vprostack_sg_out

    - name: Update Security Group with its own SG ID
      amazon.aws.ec2_group:
        name: vprostack-sg
        description: Allow Port 22 from anywhere and all port within SG
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vprostack_sg_out.group_id }}"
    
    - name: Create Nginx web01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ nginx_ami }}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: web01
          
        exact_count: 1
        count_tag:
          Name: web01
          Project: vpro
          Owner: Ammar
        group_id:
          - "{{ vprostack_sg_out.group_id }}"
        vpc_subnet_id: "{{ private_subnet1 }}"
      register: web01_out

    - name: Create Tomcat app01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ tomcat_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: app01
          Project: vprofile
          Owner: Ammar
          
        exact_count: 1
        count_tag:
          Name: app01
          Project: vpro
          Owner: Ammar
        group_id:
          - "{{ vprostack_sg_out.group_id }}"
        vpc_subnet_id: "{{ private_subnet1 }}"
      register: app01_out  

    - name: Create Memcached cache01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ memcached_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: cache01
          Project: vprofile
          Owner: Ammar
          
        exact_count: 1
        count_tag:
          Name: cache01
          Project: vpro
          Owner: Ammar
        group_id:
          - "{{ vprostack_sg_out.group_id }}"
        vpc_subnet_id: "{{ private_subnet1 }}"
      register: cache01_out

    - name: Create MYSQL db01
      amazon.aws.ec2_instance:
        key_name: vprokey
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: "{{ my_sql_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: db01
          Project: vprofile
          Owner: Ammar
          
        exact_count: 1
        count_tag:
          Name: db01
          Project: vpro
          Owner: Ammar
        group_id:
          - "{{ vprostack_sg_out.group_id }}"
        vpc_subnet_id: "{{ private_subnet1 }}"
      register: db01_out 

    - name: Print out instance IDs
      debug:
        msg: "Instance ID is {{ item.instance_ids }}"
      with_items:
        - "{{ web01_out }}"
        - "{{ app01_out }}"
        - "{{ cache01_out }}"
        - "{{ db01_out }}"