- name: Setup vprofile Stack
  hosts: localhost
  connection: local
  tasks:
    - name: import VPC setup Variables
      include_vars: vars/vpc_output_vars

    - name: Import vprofileelasticsetup Variables
      include_vars: vars/vprofileelasticsetup

    - name: create Vprofile EC2 Key .
      ec2_key:
        name: vprokey
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into file vpro-key.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginhey-vpro.pem"
        mode: 0600
      when: vprokey_out.changed
      